version: '3.1'
services:

  movie-finder:
    build: .
    container_name: movie-finder
    ports:
     - "18080:8080"
     - "18787:8787"
    depends_on:
      - mfdb
    restart: always

  mfdb:
    image: mysql:5.7
    container_name: mfdb
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mf
      MYSQL_USER: mfuser
      MYSQL_PASSWORD: mfpwd

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
    links:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: '--config.file=/etc/prometheus/prometheus.yml'