---
- hosts: web
  become: true
  gather_facts: yes
  remote_user: vagrant

  tasks:

  - name: add add-apt-repostory
    apt: pkg=software-properties-common state=present update_cache=yes
    become: true

  - name: add add-apt-repostory
    apt: pkg=python-software-properties state=present update_cache=yes
    become: true
    when: ansible_distribution_release == "trusty"

  - name: add webupd8 ppa
    apt_repository: repo='ppa:webupd8team/java'

  - name: update
    shell: apt-get update
    become: true

  - name: auto accept oracle jdk license
    shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
    become: true

  - name: install java8
    shell: apt-get install -y oracle-java8-installer ca-certificates
    become: true
