---
apiVersion: v1
kind: ConfigMap
metadata:
  name: moviefinder-mysql-configmap
  namespace: default
data:
  mysql_host: moviefinder-mysql
  mysql_port: "3306"
  mysql_database: moviefinderdb
---
apiVersion: v1
kind: Secret
metadata:
  name: moviefinder-mysql-secrets
type: Opaque
data:
  mysql_root_password: YWRtaW4= # admin
  mysql_username: c2l2YQ== # siva
  mysql_password: c2l2YWxhYnM= # sivalabs
---
